# Generated by Django 6.0.5 on 2026-05-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='side_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
