# Generated by Django 6.0.5 on 2026-06-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_list_file_list_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='file',
        ),
        migrations.RemoveField(
            model_name='list',
            name='image',
        ),
    ]
